# Generated by Django 6.0.6 on 2026-06-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='icon',
            field=models.CharField(default='gem', help_text="Font Awesome icon name, e.g. 'gem', 'rocket', 'chart-line' (without the fa- prefix)", max_length=30),
        ),
    ]
