# Generated by Django 6.0.6 on 2026-06-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sitesettings_allow_investment_cancellation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20),
        ),
    ]
