# Generated by Django 6.0.6 on 2026-06-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_blogpost_sidebarmenuitem_frontpage_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='allow_deposit_referral_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='deposit_referral_bonus_pct',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
