# Generated by Django 5.2.15 on 2026-06-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sitesettings_allow_deposit_referral_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='paystack_currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paystack_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='paystack_secret_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
