# Generated by Django 5.2.15 on 2026-06-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_card_brand_transaction_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, choices=[('bitcoin', 'Bitcoin'), ('usdt_trc20', 'USDT TRC20'), ('usdt_erc20', 'USDT ERC20'), ('ethereum', 'Ethereum'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('paystack', 'Paystack'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
