# Generated by Django 5.2.15 on 2026-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='crypto_amount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='crypto_rate_usd',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='crypto_symbol',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
